---
 homebrew_cask_packages:
  - alfred
  - caffeine
  - virtualbox
  - vagrant
  - divvy
  - flux
  - firefox
  - evernote
  - google-chrome
  - spotify
  - iterm2
  - java
  - slack
  - steam
  - skype
  - macvim
  - tunnelblick
