---
 - name: Clone dotvim repo
   git:
     repo=https://github.com/heim/dotvim.git
     dest={{lookup('env','HOME')}}/.vim

 - name: Ensure link to vimrc
   file:
      src=~/.vim/vimrc
      dest=~/.vimrc
      state=link
      force=yes
